### ISSUE TITLE
图片资源丢失

### ISSUE THREAD

**Issue by hahaCodeMan** [sonichy/HTYFileManager#1]
mac下跑起来，效果相差很大，能否把丢失资源重新提交上去?

**Comment by sonichy** [comment]
给我看截图，是不是图标没出来，没做好。
这个项目做的不好，要不要看看其他的。
Mac玩Qt有什么意思。

**Comment by hahaCodeMan** [comment]
新手找学习质料 看到的,效果如下图
![屏幕快照 2019-04-22 下午5 26 44](https://user-images.githubusercontent.com/13029857/56494435-ce8bb080-6524-11e9-86a6-966b1c41f602.png)

**Comment by sonichy** [comment]
文件图标没显示，Linux没有这个问题。
